name = 'example'
license = 'MIT'
licenselink = 'https://opensource.org/license/mit'
description = 'A concise guide to native Hugo features and good defaults.'
homepage = 'https://example.org/'
tags = ['documentation', 'example', 'responsive']
features = ['assets', 'content', 'menus', 'taxonomies']
min_version = '0.162.0'

[author]
  name = 'hugo-devkit'
